services:
  waf:
    build: ./waf
    port: 8080
    health:
      path: /health
      interval: 10
      timeout: 9
    environment:
      - CORAZA_RULE_ENGINE=On
      - ANOMALY_INBOUND=999999
      - PARANOIA=1
      - BLOCKING_PARANOIA=1
      - DETECTION_PARANOIA=1
      - BACKEND=web:3000
      - PORT=8080
    scale:
      count: 1
      cpu: 256
      memory: 512
  web:
    build: ./backend
    port: 3000
    internal: true
    scale:
      count: 1
      cpu: 256
      memory: 256
